jwt:
  secret-key: q60foyaAUohjQO24NBdN4JARYeYxi/1WbKJg03LnQ+M=
  access-token-expiration: 900000
  refresh-token-expiration: 3600000


spring:
  application:
    name: payment_gateway
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/payment_gateway_app
    username: postgres
    password: pg1234
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
  flyway:
    baseline-on-migrate: true
    enabled: true
    user: postgres
    password: pg1234
    baseline-description: "init"
    baseline-version: 1