jwt:
  secret-key: q60foyaAUohjQO24NBdN4JARYeYxi/1WbKJg03LnQ+M=
  access-token-expiration: 900000
  refresh-token-expiration: 86400000


spring:
  application:
    name: payment_gateway
  config:
    import: optional:file:.env[.properties]
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
  flyway:
    baseline-on-migrate: true
    enabled: true
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    baseline-description: "init"
    baseline-version: 1
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          ssl:
            trust: smtp.gmail.com


