
CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE TABLE users (
    id UUID PRIMARY KEY ,
    username VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL ,
    email VARCHAR(255) NOT NULL UNIQUE ,
    role VARCHAR(20) NOT NULL CHECK ( role in ('MERCHANT', 'ADMIN','DEVELOPER','CUSTOMER') ),
    is_active BOOLEAN DEFAULT true,
    email_verified BOOLEAN DEFAULT false,
    created_at  TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE refresh_token (
    id SERIAL PRIMARY KEY ,
    token VARCHAR(500) NOT NULL UNIQUE,
    issued_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    revoked BOOLEAN DEFAULT false,
    user_id UUID REFERENCES users(id) ON DELETE CASCADE
)
